replicaCount: 3

autoscaling:
  enabled: true

image:
  tag: 17-alpine
  repository: postgres
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 5432

volumeClaim:
  class: manual
  accessModes:
    - ReadWriteMany
  storage: 10Gi

config:
  database:
    name:
    password:
    username: