apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "postgres.fullname" . }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "temporal-gateway.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "temporal-gateway.selectorLabels" . | nindent 6 }}
    spec:
      containers:
        - name: postgres
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: {{ include "postgres.fullname" . }}
            - secretRef:
                name: {{ include "postgres.fullname" . }}
          volumeMounts:
            - name: {{ include "postgres.fullname" . }}
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: {{ include "postgres.fullname" . }}
          persistentVolumeClaim:
            claimName: {{ include "postgres.fullname" . }}