apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "postgres.fullname" . }}
data:
  POSTGRES_DB: {{ .Values.config.database.name | b64enc }}
  POSTGRES_PASSWORD: {{ .Values.config.database.password | b64enc }}