apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "postgres.fullname" . }}
  labels:
    {{- include "postgres.labels" . | nindent 4 }}
spec:
  storageClassName: {{ .Values.volumeClaim.class}}
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.volumeClaim.storage}}
